name: Build and Release EXE

on:
  push:
    branches:
      - main  # Replace 'main' with the branch you want to trigger the release on

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        run: python -m pip install --upgrade pip

      - name: Download Python Script from Gist
        run: curl -L -o get_tds_cert.py https://gist.githubusercontent.com/lnattrass/a4a91dbf439fc1719d69f7865c1b1791/raw/804fd5e01c124c6d3ea2726fec822ff37e99cbe3/get_tds_cert.py

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build EXE
        run: pyinstaller --onefile get_tds_cert.py

      - name: Generate Random Tag
        id: generate_tag
        run: echo "::set-output name=TAG_NAME::v$(date +'%Y%m%d%H%M%S')"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.generate_tag.outputs.TAG_NAME }}
          release_name: Automated Release ${{ steps.generate_tag.outputs.TAG_NAME }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/get_tds_cert.exe
          asset_name: get_tds_cert.exe
          asset_content_type: application/octet-stream
