name: Build and Release EXE

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4


      - name: Download Python Script from Gist
        run: |
          curl -L -o get_tds_cert.py https://gist.githubusercontent.com/lnattrass/a4a91dbf439fc1719d69f7865c1b1791/raw/804fd5e01c124c6d3ea2726fec822ff37e99cbe3/get_tds_cert.py

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --onefile get_tds_cert.py
        shell: bash

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_tag.outputs.tag_name }}
          release_name: Release ${{ steps.extract_tag.outputs.tag_name }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/get_tds_cert.exe
          asset_name: get_tds_cert.exe
          asset_content_type: application/octet-stream
